from .Blog import bp as Blog
from .Auth import bp as Auth
from .Comment import bp as Comment
from .User import bp as User_post
from .Bot import bp as Bot
from .cabinet_client.Order import bp as Order
from .cabinet_client.Cabinet import bp as Cabinet
from .cabinet_client.Admin import bp as Admin
from .cabinet_client.Product import bp as Products
from .cabinet_client.Analitic_rout import bp as Analitic
from .cabinet_client.Arrival_rout import bp as Arrival
from .cabinet_client.JourChRout import bp as JourChRout
from .cabinet_client.SourProdRout import bp as ProductSource
from .cabinet_client.Source_Difference import bp as SourceDifference
