from datetime import datetime
from server_flask.db import db


class UserToken(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    project = db.Column(db.String(150))
    user_id = db.Column(db.Integer, db.ForeignKey(
        'user.id', name='fk_drop_user_id'), nullable=False)
    np_token = db.Column(db.String(255))
    prom_token = db.Column(db.String(255))
    telegram_bot_token = db.Column(db.String(255))
    telegram_bot_token_test = db.Column(db.String(255))
    payment_token = db.Column(db.String(255))
    shop_id = db.Column(db.String(255))
    np_phone = db.Column(db.String(255))
    sms_token = db.Column(db.String(255))
    np_sender_refs = db.Column(db.String(255))
    np_count_refs = db.Column(db.String(255))
    np_city_cender = db.Column(db.String(255))
    np_adress_contr = db.Column(db.String(255))
    np_conter_recipient = db.Column(db.String(255))
    np_conter_recipient_owner_form = db.Column(db.String(255))
    np_conter_recipent_counterparty = db.Column(db.String(255))
    db_username = db.Column(db.String(255))
    db_password = db.Column(db.String(255))
    chat_id_info = db.Column(db.String(255))
    chat_id_confirmation = db.Column(db.String(255))
    chat_id_helper = db.Column(db.String(255))
    ch_id_np = db.Column(db.String(255))
    ch_id_sk = db.Column(db.String(255))
    ch_id_ukr = db.Column(db.String(255))
    ch_id_roz = db.Column(db.String(255))
    ch_id_stok = db.Column(db.String(255))
    ch_id_shop = db.Column(db.String(255))
    token_to_srm_send_with_prom = db.Column(db.String(255))
    token_to_srm_update_with_prom = db.Column(db.String(255))
    x_telegram_api_bot_token = db.Column(db.String(255))
    fromatter_log = db.Column(db.String(255))
