[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "asxcrm"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
log_cli = true
filterwarnings = [
    "ignore::DeprecationWarning"
]
addopts = [
    "--import-mode=importlib",
]