from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class UserTokenDTO(BaseModel):
    id: Optional[int]
    timestamp: Optional[datetime]
    project_id: Optional[int]
    user_id: Optional[int]
    np_token: Optional[str]
    prom_token: Optional[str]
    telegram_bot_token: Optional[str]
    telegram_bot_token_test: Optional[str]
    payment_token: Optional[str]
    shop_id: Optional[str]
    np_phone: Optional[str]
    sms_token: Optional[str]
    np_sender_refs: Optional[str]
    np_count_refs: Optional[str]
    np_city_cender: Optional[str]
    np_adress_contr: Optional[str]
    np_conter_recipient: Optional[str]
    np_conter_recipient_owner_form: Optional[str]
    np_conter_recipent_counterparty: Optional[str]
    db_username: Optional[str]
    db_password: Optional[str]
    chat_id_info: Optional[str]
    chat_id_confirmation: Optional[str]
    chat_id_helper: Optional[str]
    ch_id_np: Optional[str]
    ch_id_sk: Optional[str]
    ch_id_ukr: Optional[str]
    ch_id_roz: Optional[str]
    ch_id_stok: Optional[str]
    ch_id_shop: Optional[str]
    token_to_srm_send_with_prom: Optional[str]
    token_to_srm_update_with_prom: Optional[str]
    x_telegram_api_bot_token: Optional[str]
    fromatter_log: Optional[str]
    checkbox_license_key: Optional[str]
    checkbox_host: Optional[str]
    checkbox_client_name: Optional[str]
    checkbox_pin_cashier: Optional[str]
    checkbox_client_version: Optional[str]
    device_id: Optional[str]
    checkbox_access_token: Optional[str]
